### ISSUE TITLE
Hunt

### ISSUE THREAD

**Issue by RSNFreud** [The-Tasty-Jaffa/Freuds-Programing-help#2]
2 things

- [x] It shouldnt accept answers that are not for that current question.

- [x] It is erroring out in deleting messages in DMs. Might want to make it ignore dms completly.

**Comment by The-Tasty-Jaffa** [comment]
*shouldn't* or *should*?

As for deleting msg in DMs you can check if the message is in a private channel

**Comment by RSNFreud** [comment]
Shouldn't

**Comment by RSNFreud** [comment]
@The-Tasty-Jaffa

**Comment by The-Tasty-Jaffa** [comment]
What about it being linear (only the next "solution" has been added)
